version: 2    

updates:
  - package-ecosystem : "npm"
    directory: "./app"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
    ignore: 
      - dependency-name: "swiper"
        versions: ["9.x"]
    allow: 
      - dependency-type: "all"
    registries: "*"

    
    




