version: 2
updates:
  - package-ecosystem : "npm"
    directory: "./app"
    schedule:
      interval: "weekly"
    ignore: 
      - dependency-name: "swiper"
        versions: ["9.x"]
    allow: 
      - dependency-type: "all"
    commit-message:
      include: "scope"
    




