
name: Merge dependabot PRs into one PR
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 1'

permissions:
  contents: write
  pull-requests: write

jobs:
  combineAndTicket:
    runs-on: ubuntu-latest
    steps:
      - name: GHA-combine-PRs
        uses: vic1707/GHA-combine-PRs@1.1.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          branch-prefix: dependabot/npm_and_yarn
          combine-branch-name: 'combine'
          ignore-label: nocombine
          must-be-green: false
          min-prs: 1

